---
- include: ec2.yml
- include: security_groups.yml
- include: rds.yml
  when: replicator
- include: elb.yml
- include: directory_structure.yml
- include: ssh.yml
- include: replication.yml
  when: replicator
- include: deploy.yml
  when: replicator
- include: restart.yml
- include: elb_insert.yml
  when: replicator != True
