---
- name: Create RDS security group
  ec2_group:
    name: Wordpress
    description: Wordpress database
    vpc_id: "{{ wp_vpc_id }}"
    region: "{{ ansible_ec2_placement_region }}"
    rules:
      - proto: tcp
        from_port: 3306
        to_port: 3306
        cidr_ip: "{{ internal_network_cidr }}"
  register: sg

- name: Create load balancer security group
  ec2_group:
    name: Wordpress-LB
    description: "Wordpress load balancer"
    vpc_id: "{{ wp_vpc_id }}"
    region: "{{ ansible_ec2_placement_region }}"
    rules:
      - proto: all
        from_port: 80
        to_port: 80
        cidr_ip: "0.0.0.0/0"
  ignore_errors: Yes
  register: lb_sg

- name: Allow access to web instances via load balancer
  ec2_group:
    name: Web
    description: "Wordpress web"
    vpc_id: "{{ wp_vpc_id }}"
    region: "{{ ansible_ec2_placement_region }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: "{{ internal_network_cidr }}"
      - proto: tcp
        from_port: 80
        to_port: 80
        group_id: "{{ lb_sg.group_id }}"
